### ISSUE TITLE
Missing open source license?

### ISSUE THREAD

**Issue by kfogel** [pjsier/chisafepath#7]
Hi, Steven and Patrick.  This software is intended to be open source, right?  If that's correct, it should ideally have an explicit LICENSE.md file at the top level.  http://choosealicense.com/ can help if you're not sure which license to choose, and see https://opensource.org/faq#apply-license on how to apply a license to your software.  I can submit a PR, if you tell me which license.

**Comment by pjsier** [comment]
Good catch! I just added the MIT License

**Comment by kfogel** [comment]
W00t -- thanks for the fast fix!
